name: "library-system"

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: iLuvBooks4ever<3
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
  reservationapi:
    build:
      context: .
      dockerfile: ReservationAPI/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - database
    # deploy:
    #   replicas: 2
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:5341"
      - "5342:80"
    volumes:
      - seq-data:/data
    depends_on:
      - reservationapi
    environment:
      ACCEPT_EULA: "Y"

volumes:
  seq-data: